### ISSUE TITLE
Use travis CI and run shellcheck

### ISSUE THREAD

**Issue by Artoria2e5** [MagicNAT/shadowmanager#3]
https://github.com/caarlos0/shell-ci-build
https://github.com/koalaman/shellcheck/wiki/TravisCI

**Comment by magicnat** [comment]
Actually I used to thought about it too. However, travis-ci does not show my public repo there, got any idea why that happen?

**Comment by Artoria2e5** [comment]
(What should I say? "Give me your GitHub password and $344?")

**Comment by magicnat** [comment]
¯\_(ツ)_/¯ That doesn't seems to be a solution. 
I gonna ask travis-ci about it.
